### ISSUE TITLE
Horizontal scroll when window greater than ~994px wide.

### ISSUE THREAD

**Issue by sstiglitz** [app-generator/django-volt-dashboard-pro2#2]
Steps:

1. Open the live demo https://tb-volt-dashboard-pro-django.appseed-srv1.com/dashboard.html
2. Set browser window > about 994px wide. I'm not sure the exact media break, but it is close to 994px
3. Observe the window

Expected
Since there is no content to the right, no x-axis scrollbar is present.

Actual
There is a scrollbar present. 

This isn't specific to the `dashboard.html` page, I observed the same in other screens.

![Screenshot example of scrollbar present](https://i.imgur.com/nukrL6I.png)

**Comment by app-generator** [comment]
Hello @sstiglitz, 

Thank you for reporting this issue. 
This problem is already tracked internally.  We will update the kit once Themesberg provides the fix. 

We have a workaround fix - but is just a temporary patch. 
Let us know if this problem is a blocking point for your project. 

**AppSeed Support**

**Comment by app-generator** [comment]
Fixed in **v1.0.4**
